# Generated by Django 5.2.7 on 2025-10-04 18:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import problems.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('usage_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('time_limit', models.IntegerField(default=1000)),
                ('memory_limit', models.IntegerField(default=256)),
                ('max_score', models.IntegerField(default=100)),
                ('is_public', models.BooleanField(default=False)),
                ('total_submissions', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('accepted_submissions', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('acceptance_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('like_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('view_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_quota', models.IntegerField(default=-1, validators=[problems.models.unlimited_or_nonnegative])),
                ('description', models.TextField()),
                ('input_description', models.TextField(blank=True, null=True)),
                ('output_description', models.TextField(blank=True, null=True)),
                ('sample_input', models.TextField(blank=True, null=True)),
                ('sample_output', models.TextField(blank=True, null=True)),
                ('hint', models.TextField(blank=True, null=True)),
                ('test_case_info', models.TextField(blank=True, null=True)),
                ('supported_languages', models.JSONField(default=problems.models.default_supported_langs)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='courses.courses')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_problems', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_problem_tags', to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.tag')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(related_name='problems', through='problems.ProblemTag', to='problems.tag'),
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('case_no', models.IntegerField()),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('weight', models.IntegerField(default=1)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('case_group', models.IntegerField(default=1)),
                ('file_size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='problems.problem')),
            ],
        ),
        migrations.AddIndex(
            model_name='problemtag',
            index=models.Index(fields=['tag'], name='problems_pr_tag_id_c16115_idx'),
        ),
        migrations.AddIndex(
            model_name='problemtag',
            index=models.Index(fields=['problem', 'tag'], name='problems_pr_problem_43ff91_idx'),
        ),
        migrations.AddConstraint(
            model_name='problemtag',
            constraint=models.UniqueConstraint(fields=('problem', 'tag'), name='uq_problem_tag'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['difficulty'], name='problems_pr_difficu_d3b056_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['is_public'], name='problems_pr_is_publ_b35f8d_idx'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['problem', 'case_group'], name='problems_te_problem_f850f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='testcase',
            constraint=models.UniqueConstraint(fields=('problem', 'case_no'), name='uq_problem_case_no'),
        ),
    ]
