# Generated by Django 5.2.7 on 2025-11-14 21:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import problems.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('usage_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('max_score', models.IntegerField(default=100)),
                ('is_public', models.CharField(choices=[('hidden', 'Hidden'), ('course', 'Course only'), ('public', 'Public')], db_index=True, default='hidden', max_length=10)),
                ('total_submissions', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('accepted_submissions', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('acceptance_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('like_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('view_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_quota', models.IntegerField(default=-1, help_text='The maximum number of submissions allowed for this problem. Set to -1 for unlimited submissions.', validators=[problems.models.unlimited_or_nonnegative])),
                ('description', models.TextField()),
                ('input_description', models.TextField(blank=True, null=True)),
                ('output_description', models.TextField(blank=True, null=True)),
                ('sample_input', models.TextField(blank=True, null=True)),
                ('sample_output', models.TextField(blank=True, null=True)),
                ('hint', models.TextField(blank=True, null=True)),
                ('subtask_description', models.TextField(blank=True, null=True)),
                ('supported_languages', models.JSONField(default=problems.models.default_supported_langs)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.courses')),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_problems', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Problem_tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_problem_tags', to=settings.AUTH_USER_MODEL)),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problems')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.tags')),
            ],
        ),
        migrations.CreateModel(
            name='Problem_subtasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subtask_no', models.PositiveIntegerField()),
                ('weight', models.IntegerField(default=0)),
                ('time_limit_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('memory_limit_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='problems.problems')),
            ],
            options={
                'db_table': 'problem_subtasks',
            },
        ),
        migrations.AddField(
            model_name='problems',
            name='tags',
            field=models.ManyToManyField(related_name='problems', through='problems.Problem_tags', to='problems.tags'),
        ),
        migrations.CreateModel(
            name='Test_cases',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idx', models.PositiveIntegerField()),
                ('input_path', models.CharField(blank=True, max_length=500, null=True)),
                ('output_path', models.CharField(blank=True, max_length=500, null=True)),
                ('input_size', models.PositiveIntegerField(default=0)),
                ('output_size', models.PositiveIntegerField(default=0)),
                ('checksum_in', models.CharField(blank=True, max_length=64, null=True)),
                ('checksum_out', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('ready', 'ready')], db_index=True, default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subtask_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='problems.problem_subtasks')),
            ],
            options={
                'db_table': 'test_cases',
            },
        ),
        migrations.CreateModel(
            name='ProblemLike',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='problems.problems')),
            ],
            options={
                'db_table': 'problem_likes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['problem', 'user'], name='problem_lik_problem_f9cd4f_idx'), models.Index(fields=['user', 'created_at'], name='problem_lik_user_id_27fbcd_idx')],
                'constraints': [models.UniqueConstraint(fields=('problem', 'user'), name='unique_problem_user_like')],
            },
        ),
        migrations.AddIndex(
            model_name='problem_subtasks',
            index=models.Index(fields=['problem_id'], name='problem_sub_problem_0ad870_idx'),
        ),
        migrations.AddConstraint(
            model_name='problem_subtasks',
            constraint=models.UniqueConstraint(fields=('problem_id', 'subtask_no'), name='uniq_problem_subtask_no'),
        ),
        migrations.AddConstraint(
            model_name='problem_subtasks',
            constraint=models.CheckConstraint(condition=models.Q(('subtask_no__gte', 1), ('subtask_no__lte', 99)), name='chk_subtask_no_1_99'),
        ),
        migrations.AddIndex(
            model_name='problems',
            index=models.Index(fields=['difficulty'], name='problems_pr_difficu_8d904b_idx'),
        ),
        migrations.AddIndex(
            model_name='problems',
            index=models.Index(fields=['is_public'], name='problems_pr_is_publ_765cb6_idx'),
        ),
        migrations.AddIndex(
            model_name='problem_tags',
            index=models.Index(fields=['tag_id'], name='problems_pr_tag_id__d1850f_idx'),
        ),
        migrations.AddIndex(
            model_name='problem_tags',
            index=models.Index(fields=['problem_id', 'tag_id'], name='problems_pr_problem_533a98_idx'),
        ),
        migrations.AddConstraint(
            model_name='problem_tags',
            constraint=models.UniqueConstraint(fields=('problem_id', 'tag_id'), name='uq_problem_tag'),
        ),
        migrations.AddIndex(
            model_name='test_cases',
            index=models.Index(fields=['subtask_id', 'status'], name='test_cases_subtask_359a35_idx'),
        ),
        migrations.AddConstraint(
            model_name='test_cases',
            constraint=models.UniqueConstraint(fields=('subtask_id', 'idx'), name='uniq_subtask_idx'),
        ),
        migrations.AddConstraint(
            model_name='test_cases',
            constraint=models.CheckConstraint(condition=models.Q(('idx__gte', 1), ('idx__lte', 99)), name='chk_idx_1_99'),
        ),
        migrations.AddConstraint(
            model_name='test_cases',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'draft'), models.Q(('status', 'ready'), models.Q(('input_path__isnull', True), ('output_path__isnull', True), ('input_path', ''), ('output_path', ''), _connector='OR', _negated=True)), _connector='OR'), name='chk_ready_requires_both_paths'),
        ),
    ]
