# Generated by Django 5.2.7 on 2025-12-03 14:54

import django.core.validators
import django.utils.timezone
import problems.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem_subtasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subtask_no', models.PositiveIntegerField()),
                ('weight', models.IntegerField(default=0)),
                ('time_limit_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('memory_limit_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'problem_subtasks',
            },
        ),
        migrations.CreateModel(
            name='Problem_tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemLike',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'problem_likes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('max_score', models.IntegerField(default=100)),
                ('is_public', models.CharField(choices=[('hidden', 'Hidden'), ('course', 'Course only'), ('public', 'Public')], db_index=True, default='hidden', max_length=10)),
                ('total_submissions', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('accepted_submissions', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('acceptance_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('like_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('view_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_quota', models.IntegerField(default=-1, help_text='The maximum number of submissions allowed for this problem. Set to -1 for unlimited submissions.', validators=[problems.models.unlimited_or_nonnegative])),
                ('description', models.TextField()),
                ('input_description', models.TextField(blank=True, null=True)),
                ('output_description', models.TextField(blank=True, null=True)),
                ('sample_input', models.TextField(blank=True, null=True)),
                ('sample_output', models.TextField(blank=True, null=True)),
                ('hint', models.TextField(blank=True, null=True)),
                ('subtask_description', models.TextField(blank=True, null=True)),
                ('supported_languages', models.JSONField(default=problems.models.default_supported_langs)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('usage_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Test_cases',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idx', models.PositiveIntegerField()),
                ('input_path', models.CharField(blank=True, max_length=500, null=True)),
                ('output_path', models.CharField(blank=True, max_length=500, null=True)),
                ('input_size', models.PositiveIntegerField(default=0)),
                ('output_size', models.PositiveIntegerField(default=0)),
                ('checksum_in', models.CharField(blank=True, max_length=64, null=True)),
                ('checksum_out', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('ready', 'ready')], db_index=True, default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'test_cases',
            },
        ),
    ]
