# Generated by Django 5.2.7 on 2025-10-07 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem_subtasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subtask_no', models.PositiveIntegerField()),
                ('weight', models.IntegerField(default=0)),
                ('time_limit_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('memory_limit_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'problem_subtasks',
            },
        ),
        migrations.RemoveConstraint(
            model_name='test_cases',
            name='uq_problem_case_no',
        ),
        migrations.RemoveIndex(
            model_name='test_cases',
            name='problems_te_problem_d58636_idx',
        ),
        migrations.RenameField(
            model_name='test_cases',
            old_name='file_path',
            new_name='input_path',
        ),
        migrations.RemoveField(
            model_name='test_cases',
            name='case_group',
        ),
        migrations.RemoveField(
            model_name='test_cases',
            name='expected_output',
        ),
        migrations.RemoveField(
            model_name='test_cases',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='test_cases',
            name='input_data',
        ),
        migrations.RemoveField(
            model_name='test_cases',
            name='problem_id',
        ),
        migrations.RemoveField(
            model_name='test_cases',
            name='weight',
        ),
        migrations.AddField(
            model_name='test_cases',
            name='checksum_in',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='test_cases',
            name='checksum_out',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='test_cases',
            name='idx',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test_cases',
            name='input_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test_cases',
            name='output_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='test_cases',
            name='output_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test_cases',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('ready', 'ready')], db_index=True, default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='test_cases',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterModelTable(
            name='test_cases',
            table='test_cases',
        ),
        migrations.AddField(
            model_name='problem_subtasks',
            name='problem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='problems.problems'),
        ),
        migrations.AddField(
            model_name='test_cases',
            name='subtask_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='problems.problem_subtasks'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='test_cases',
            index=models.Index(fields=['subtask_id', 'status'], name='test_cases_subtask_359a35_idx'),
        ),
        migrations.AddConstraint(
            model_name='test_cases',
            constraint=models.UniqueConstraint(fields=('subtask_id', 'idx'), name='uniq_subtask_idx'),
        ),
        migrations.AddConstraint(
            model_name='test_cases',
            constraint=models.CheckConstraint(condition=models.Q(('idx__gte', 1), ('idx__lte', 99)), name='chk_idx_1_99'),
        ),
        migrations.AddConstraint(
            model_name='test_cases',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'draft'), models.Q(('status', 'ready'), models.Q(('input_path__isnull', True), ('output_path__isnull', True), ('input_path', ''), ('output_path', ''), _connector='OR', _negated=True)), _connector='OR'), name='chk_ready_requires_both_paths'),
        ),
        migrations.AddIndex(
            model_name='problem_subtasks',
            index=models.Index(fields=['problem_id'], name='problem_sub_problem_0ad870_idx'),
        ),
        migrations.AddConstraint(
            model_name='problem_subtasks',
            constraint=models.UniqueConstraint(fields=('problem_id', 'subtask_no'), name='uniq_problem_subtask_no'),
        ),
        migrations.AddConstraint(
            model_name='problem_subtasks',
            constraint=models.CheckConstraint(condition=models.Q(('subtask_no__gte', 1), ('subtask_no__lte', 99)), name='chk_subtask_no_1_99'),
        ),
    ]
