# Generated by Django 5.2.7 on 2025-12-28 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='problem_tags',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_problem_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problemlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problems',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.courses'),
        ),
        migrations.AddField(
            model_name='problems',
            name='creator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_problems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problemlike',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='problems.problems'),
        ),
        migrations.AddField(
            model_name='problem_tags',
            name='problem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problems'),
        ),
        migrations.AddField(
            model_name='problem_subtasks',
            name='problem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='problems.problems'),
        ),
        migrations.AddField(
            model_name='problems',
            name='tags',
            field=models.ManyToManyField(related_name='problems', through='problems.Problem_tags', to='problems.tags'),
        ),
        migrations.AddField(
            model_name='problem_tags',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.tags'),
        ),
        migrations.AddField(
            model_name='test_cases',
            name='subtask_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='problems.problem_subtasks'),
        ),
        migrations.AddIndex(
            model_name='problemlike',
            index=models.Index(fields=['problem', 'user'], name='problem_lik_problem_f9cd4f_idx'),
        ),
        migrations.AddIndex(
            model_name='problemlike',
            index=models.Index(fields=['user', 'created_at'], name='problem_lik_user_id_27fbcd_idx'),
        ),
        migrations.AddConstraint(
            model_name='problemlike',
            constraint=models.UniqueConstraint(fields=('problem', 'user'), name='unique_problem_user_like'),
        ),
        migrations.AddIndex(
            model_name='problem_subtasks',
            index=models.Index(fields=['problem_id'], name='problem_sub_problem_0ad870_idx'),
        ),
        migrations.AddConstraint(
            model_name='problem_subtasks',
            constraint=models.UniqueConstraint(fields=('problem_id', 'subtask_no'), name='uniq_problem_subtask_no'),
        ),
        migrations.AddConstraint(
            model_name='problem_subtasks',
            constraint=models.CheckConstraint(condition=models.Q(('subtask_no__gte', 1), ('subtask_no__lte', 99)), name='chk_subtask_no_1_99'),
        ),
        migrations.AddIndex(
            model_name='problems',
            index=models.Index(fields=['difficulty'], name='problems_pr_difficu_8d904b_idx'),
        ),
        migrations.AddIndex(
            model_name='problems',
            index=models.Index(fields=['is_public'], name='problems_pr_is_publ_765cb6_idx'),
        ),
        migrations.AddConstraint(
            model_name='problems',
            constraint=models.CheckConstraint(condition=models.Q(('solution_code__isnull', True), ('solution_code', ''), models.Q(models.Q(('solution_code_language__isnull', True), _negated=True), models.Q(('solution_code_language', ''), _negated=True)), _connector='OR'), name='chk_solution_lang_required_when_code_present'),
        ),
        migrations.AddIndex(
            model_name='problem_tags',
            index=models.Index(fields=['tag_id'], name='problems_pr_tag_id__d1850f_idx'),
        ),
        migrations.AddIndex(
            model_name='problem_tags',
            index=models.Index(fields=['problem_id', 'tag_id'], name='problems_pr_problem_533a98_idx'),
        ),
        migrations.AddConstraint(
            model_name='problem_tags',
            constraint=models.UniqueConstraint(fields=('problem_id', 'tag_id'), name='uq_problem_tag'),
        ),
        migrations.AddIndex(
            model_name='test_cases',
            index=models.Index(fields=['subtask_id', 'status'], name='test_cases_subtask_359a35_idx'),
        ),
        migrations.AddConstraint(
            model_name='test_cases',
            constraint=models.UniqueConstraint(fields=('subtask_id', 'idx'), name='uniq_subtask_idx'),
        ),
        migrations.AddConstraint(
            model_name='test_cases',
            constraint=models.CheckConstraint(condition=models.Q(('idx__gte', 1), ('idx__lte', 99)), name='chk_idx_1_99'),
        ),
        migrations.AddConstraint(
            model_name='test_cases',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'draft'), models.Q(('status', 'ready'), models.Q(('input_path__isnull', True), ('output_path__isnull', True), ('input_path', ''), ('output_path', ''), _connector='OR', _negated=True)), _connector='OR'), name='chk_ready_requires_both_paths'),
        ),
    ]
