# Generated by Django 5.2.7 on 2025-12-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='checker_name',
            field=models.CharField(blank=True, default='diff', help_text="Name of the checker to use. 'diff' is the standard default checker when use_custom_checker is False. Common values: 'diff' (exact text match, default), 'float' (floating-point comparison), 'token' (token-based), 'custom' (problem-specific).", max_length=100),
        ),
        migrations.AddField(
            model_name='problems',
            name='use_custom_checker',
            field=models.BooleanField(default=False, help_text='Whether to use a custom checker instead of the default diff comparison.'),
        ),
    ]
