# Generated by Django 5.2.7 on 2025-12-12 18:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('problems', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='solution_code',
            field=models.TextField(blank=True, help_text='Optional: reference solution code used for test generation.', null=True),
        ),
        migrations.AddField(
            model_name='problems',
            name='solution_code_language',
            field=models.CharField(blank=True, help_text='Optional: language of solution code. Required if solution code is provided.', max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='problems',
            constraint=models.CheckConstraint(condition=models.Q(('solution_code__isnull', True), ('solution_code', ''), models.Q(models.Q(('solution_code_language__isnull', True), _negated=True), models.Q(('solution_code_language', ''), _negated=True)), _connector='OR'), name='chk_solution_lang_required_when_code_present'),
        ),
    ]
