# Generated by Django 5.2.7 on 2025-10-15 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_problem_subtasks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problems',
            old_name='test_case_info',
            new_name='subtask_description',
        ),

        # 再移除 Problems 的限制欄位（改用子題限制）
        migrations.RemoveField(
            model_name='problems',
            name='time_limit',
        ),
        migrations.RemoveField(
            model_name='problems',
            name='memory_limit',
        ),
    ]
