# Generated by Django 5.2.7 on 2025-12-29

from django.db import migrations, models


def default_allowed_network():
    return []


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_problems_checker_name_problems_use_custom_checker'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='allowed_network',
            field=models.JSONField(default=default_allowed_network),
        ),
    ]
