# Generated by Django 5.2.7 on 2025-12-28 06:49

import problems.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_problems_checker_name_problems_use_custom_checker'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='forbidden_functions',
            field=models.JSONField(blank=True, default=problems.models.default_forbidden_functions, help_text="List of function names that are forbidden when 'forbid-functions' rule is enabled. Required if 'forbid-functions' is in static_analysis_rules."),
        ),
        migrations.AddField(
            model_name='problems',
            name='static_analysis_rules',
            field=models.JSONField(blank=True, default=problems.models.default_static_analysis_rules, help_text="List of static analysis rules to apply. Valid values: 'forbid-loops', 'forbid-arrays', 'forbid-stl', 'forbid-functions'. Empty list means no static analysis."),
        ),
    ]
