# Generated by Django 5.2.7 on 2025-12-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_problems_forbidden_functions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='testcase_hash',
            field=models.CharField(blank=True, help_text='SHA256 hash of the testcase package (problem.zip). Updated when testcases are uploaded.', max_length=64, null=True),
        ),
    ]
