# Generated by Django 5.2.7 on 2025-11-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_set_course_nonnull_and_backfill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='is_public',
            field=models.CharField(choices=[('hidden', 'Hidden'), ('course', 'Course only'), ('public', 'Public')], db_index=True, default='hidden', max_length=10),
        ),
    ]
