# Generated by Django 5.2.7 on 2025-12-28 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_problems_allowed_network'),
        ('problems', '0005_add_testcase_hash'),
    ]

    operations = [
    ]
