# Generated by Django 5.2.7 on 2025-11-09 18:50

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='例如：我的筆電 CLI、CI/CD 系統', max_length=100, verbose_name='Token 名稱')),
                ('token_hash', models.CharField(max_length=64, unique=True, verbose_name='Token Hash')),
                ('prefix', models.CharField(db_index=True, help_text='用於識別 Token 的前幾位字元', max_length=32, verbose_name='Token 前綴')),
                ('permissions', models.JSONField(blank=True, default=list, verbose_name='權限列表 (Scopes)')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用次數')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最後使用時間')),
                ('last_used_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='最後使用 IP')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='建立時間')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='過期時間')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
            ],
            options={
                'verbose_name': 'API Token',
                'verbose_name_plural': 'API Tokens',
                'db_table': 'api_tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
