# Generated by Django 5.2.7 on 2025-11-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tokens', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitoken',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次使用時間'),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='last_used_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='上次使用 IP'),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, verbose_name='使用次數'),
        ),
    ]
