# Generated by Django 5.2.7 on 2025-11-23 11:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('problem_id', models.IntegerField()),
                ('assignment_id', models.IntegerField(blank=True, null=True)),
                ('language_type', models.IntegerField(choices=[(0, 'C'), (1, 'C++'), (2, 'Python'), (3, 'Java'), (4, 'JavaScript')])),
                ('source_code', models.TextField()),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('auto_saved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'code_drafts',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'problem_id', 'updated_at'], name='code_drafts_user_id_c5786c_idx'), models.Index(fields=['user', 'assignment_id', 'updated_at'], name='code_drafts_user_id_31bc95_idx')],
            },
        ),
    ]
