# Generated by Django 5.2.7 on 2025-12-03 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='codedraft',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='codedraft',
            index=models.Index(fields=['user', 'problem_id', 'updated_at'], name='code_drafts_user_id_c5786c_idx'),
        ),
        migrations.AddIndex(
            model_name='codedraft',
            index=models.Index(fields=['user', 'assignment_id', 'updated_at'], name='code_drafts_user_id_31bc95_idx'),
        ),
    ]
