# Generated by Django 5.2.7 on 2025-12-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CopycatReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.IntegerField(db_index=True, verbose_name='題目 ID')),
                ('moss_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='MOSS 報告網址')),
                ('status', models.CharField(choices=[('pending', '處理中'), ('success', '成功'), ('failed', '失敗')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'copycat_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
