# Generated by Django 5.2.7 on 2025-11-30 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copycat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='copycatreport',
            name='moss_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='MOSS 報告網址'),
        ),
        migrations.AddIndex(
            model_name='copycatreport',
            index=models.Index(fields=['problem_id', 'status'], name='copycat_rep_problem_ddfc68_idx'),
        ),
    ]
