# Generated by Django 5.2.7 on 2025-10-08 08:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Token 名稱')),
                ('permissions', models.JSONField(default=list, verbose_name='權限列表')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用次數')),
                ('usage_time', models.IntegerField(default=0, verbose_name='總使用時間(秒)')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最後使用時間')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='建立時間')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='過期時間')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL, verbose_name='關聯使用者')),
            ],
            options={
                'verbose_name': 'API Token',
                'verbose_name_plural': 'API Tokens',
                'db_table': 'Api_tokens',
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='嘗試登入的用戶名')),
                ('login_status', models.CharField(choices=[('success', '成功'), ('failed', '失敗'), ('blocked', '被阻擋')], max_length=20, verbose_name='登入狀態')),
                ('failure_reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='失敗原因')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP 位址')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登入時間')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_logs', to=settings.AUTH_USER_MODEL, verbose_name='登入使用者')),
            ],
            options={
                'verbose_name': '登入日誌',
                'verbose_name_plural': '登入日誌',
                'db_table': 'Login_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', '登入'), ('logout', '登出'), ('submit', '提交程式碼'), ('solve', '解題'), ('join_course', '加入課程'), ('create_problem', '建立題目')], max_length=50, verbose_name='活動類型')),
                ('object_type', models.CharField(blank=True, choices=[('problem', '題目'), ('assignment', '作業'), ('course', '課程'), ('submission', '提交')], max_length=50, null=True, verbose_name='關聯對象類型')),
                ('object_id', models.UUIDField(blank=True, null=True, verbose_name='關聯對象 ID')),
                ('description', models.CharField(max_length=500, verbose_name='活動描述')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP 位址')),
                ('metadata', models.JSONField(default=dict, verbose_name='額外資料')),
                ('success', models.BooleanField(default=True, verbose_name='操作是否成功')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='活動時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='操作使用者')),
            ],
            options={
                'verbose_name': '使用者活動',
                'verbose_name_plural': '使用者活動紀錄',
                'db_table': 'User_activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
