# Generated by Django 5.2.7 on 2025-10-18 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='例如：我的筆電 CLI、CI/CD 系統', max_length=100, verbose_name='Token 名稱')),
                ('token_hash', models.CharField(max_length=64, unique=True, verbose_name='Token Hash')),
                ('prefix', models.CharField(db_index=True, help_text='用於識別 Token 的前幾位字元', max_length=32, verbose_name='Token 前綴')),
                ('permissions', models.JSONField(blank=True, default=list, verbose_name='權限列表 (Scopes)')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用次數')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最後使用時間')),
                ('last_used_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='最後使用 IP')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='建立時間')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='過期時間')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL, verbose_name='關聯使用者')),
            ],
            options={
                'verbose_name': 'API Token',
                'verbose_name_plural': 'API Tokens',
                'db_table': 'api_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150, verbose_name='嘗試用戶名')),
                ('login_status', models.CharField(choices=[('success', '成功'), ('failed_credentials', '密碼錯誤'), ('failed_user_not_found', '用戶不存在'), ('blocked_ip', 'IP 被封鎖'), ('blocked_account', '帳號被停用')], max_length=30, verbose_name='登入狀態')),
                ('ip_address', models.GenericIPAddressField(verbose_name='來源 IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User-Agent')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='地理位置估計')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='登入時間')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_logs', to=settings.AUTH_USER_MODEL, verbose_name='關聯使用者')),
            ],
            options={
                'verbose_name': '登入日誌',
                'verbose_name_plural': '登入日誌',
                'db_table': 'login_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ip_address', '-created_at'], name='login_logs_ip_addr_4b8fb3_idx'), models.Index(fields=['username', '-created_at'], name='login_logs_usernam_6ed3f5_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', '登入'), ('logout', '登出'), ('submit', '提交程式碼'), ('view_problem', '查看題目'), ('download_testcase', '下載測試測資')], db_index=True, max_length=50, verbose_name='活動類型')),
                ('object_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='關聯對象 ID')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='活動補充描述')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 位址')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User-Agent')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='額外資料 (例如提交語言、檔案大小)')),
                ('success', models.BooleanField(default=True, verbose_name='操作是否成功')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='活動時間')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='操作使用者')),
            ],
            options={
                'verbose_name': '使用者活動',
                'verbose_name_plural': '使用者活動紀錄',
                'db_table': 'user_activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='user_activi_user_id_47a698_idx')],
            },
        ),
    ]