# Generated by Django 5.2.7 on 2025-11-17 13:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150, verbose_name='嘗試用戶名')),
                ('login_status', models.CharField(choices=[('success', '成功'), ('failed_credentials', '密碼錯誤'), ('failed_user_not_found', '用戶不存在'), ('blocked_ip', 'IP 被封鎖'), ('blocked_account', '帳號被停用')], max_length=30, verbose_name='登入狀態')),
                ('ip_address', models.GenericIPAddressField(verbose_name='來源 IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User-Agent')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='地理位置估計')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='登入時間')),
            ],
            options={
                'verbose_name': 'Login Log',
                'verbose_name_plural': 'Login Logs',
                'db_table': 'login_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', '登入'), ('logout', '登出'), ('submit', '提交程式碼'), ('view_problem', '查看題目'), ('download_testcase', '下載測試測資')], db_index=True, max_length=50, verbose_name='活動類型')),
                ('object_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='關聯對象 ID')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='活動補充描述')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 位址')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User-Agent')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='額外資料 (例如提交語言、檔案大小)')),
                ('success', models.BooleanField(default=True, verbose_name='操作是否成功')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='活動時間')),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'db_table': 'user_activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
