# Generated by Django 5.2.7 on 2025-11-06 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Login Log', 'verbose_name_plural': 'Login Logs'},
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Activity', 'verbose_name_plural': 'User Activities'},
        ),
    ]
