# Generated by Django 5.2.7 on 2025-11-23 11:41

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('problem_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('difficulty_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('likes_count', models.IntegerField(default=0)),
                ('views_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_official', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'editorials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EditorialLike',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='submissions.editorial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'editorial_likes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('problem_id', models.IntegerField()),
                ('language_type', models.IntegerField(choices=[(0, 'C'), (1, 'C++'), (2, 'Python'), (3, 'Java'), (4, 'JavaScript')])),
                ('source_code', models.TextField()),
                ('code_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('-2', 'Pending before upload'), ('-1', 'Pending'), ('0', 'Accepted'), ('1', 'Wrong Answer'), ('2', 'Compilation Error'), ('3', 'Time Limit Exceeded'), ('4', 'Memory Limit Exceeded'), ('5', 'Runtime Error'), ('6', 'Judge Error'), ('7', 'Output Limit Exceeded')], default='-1', max_length=30)),
                ('score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=100)),
                ('execution_time', models.IntegerField(default=-1)),
                ('memory_usage', models.IntegerField(default=-1)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('is_late', models.BooleanField(default=False)),
                ('is_custom_test', models.BooleanField(default=False)),
                ('penalty_applied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('attempt_number', models.IntegerField(default=1)),
                ('judge_server', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('judged_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('problem_id', models.IntegerField()),
                ('test_case_id', models.IntegerField()),
                ('test_case_index', models.IntegerField()),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer'), ('time_limit_exceeded', 'Time Limit Exceeded'), ('memory_limit_exceeded', 'Memory Limit Exceeded'), ('runtime_error', 'Runtime Error')], max_length=30)),
                ('execution_time', models.IntegerField(blank=True, null=True)),
                ('memory_usage', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=100)),
                ('output_preview', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('judge_message', models.TextField(blank=True, null=True)),
                ('solve_status', models.CharField(choices=[('unsolved', 'Unsolved'), ('partial', 'Partial'), ('solved', 'Solved')], default='unsolved', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='submissions.submission')),
            ],
            options={
                'db_table': 'submission_results',
                'ordering': ['test_case_index'],
            },
        ),
        migrations.CreateModel(
            name='UserProblemQuota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('problem_id', models.IntegerField()),
                ('assignment_id', models.IntegerField(blank=True, null=True)),
                ('total_quota', models.IntegerField(default=-1)),
                ('remaining_attempts', models.IntegerField(default=-1)),
                ('reset_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_problem_quotas',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProblemSolveStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('problem_id', models.IntegerField()),
                ('total_submissions', models.IntegerField(default=0)),
                ('ac_submissions', models.IntegerField(default=0)),
                ('best_score', models.IntegerField(default=0)),
                ('first_solve_time', models.DateTimeField(blank=True, null=True)),
                ('last_submission_time', models.DateTimeField(blank=True, null=True)),
                ('solve_status', models.CharField(choices=[('never_tried', 'Never Tried'), ('attempted', 'Attempted'), ('partial_solved', 'Partial Solved'), ('fully_solved', 'Fully Solved')], default='never_tried', max_length=20)),
                ('total_execution_time', models.BigIntegerField(default=0)),
                ('best_execution_time', models.IntegerField(blank=True, null=True)),
                ('best_memory_usage', models.IntegerField(blank=True, null=True)),
                ('difficulty_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('tags_mastered', models.JSONField(default=dict)),
                ('mistake_patterns', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_problem_solve_status',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProblemStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_id', models.IntegerField()),
                ('problem_id', models.IntegerField()),
                ('total_submissions', models.IntegerField(default=0)),
                ('best_score', models.IntegerField(default=0)),
                ('max_possible_score', models.IntegerField(default=100)),
                ('first_ac_time', models.DateTimeField(blank=True, null=True)),
                ('last_submission_time', models.DateTimeField(blank=True, null=True)),
                ('solve_status', models.CharField(choices=[('unsolved', 'Unsolved'), ('partial', 'Partial'), ('solved', 'Solved')], default='unsolved', max_length=20)),
                ('best_execution_time', models.IntegerField(blank=True, null=True)),
                ('best_memory_usage', models.IntegerField(blank=True, null=True)),
                ('penalty_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('is_late', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('best_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_for_stats', to='submissions.submission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_problem_stats',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('problem_id', models.IntegerField()),
                ('language_type', models.IntegerField(choices=[(0, 'C'), (1, 'C++'), (2, 'Python'), (3, 'Java'), (4, 'JavaScript')])),
                ('source_code', models.TextField()),
                ('input_data', models.TextField(blank=True, null=True)),
                ('expected_output', models.TextField(blank=True, null=True)),
                ('actual_output', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20)),
                ('execution_time', models.IntegerField(blank=True, null=True)),
                ('memory_usage', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'custom_tests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='custom_test_user_id_4c32a4_idx'), models.Index(fields=['problem_id', 'created_at'], name='custom_test_problem_129fe5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='editorial',
            index=models.Index(fields=['problem_id', 'is_official'], name='editorials_problem_79b740_idx'),
        ),
        migrations.AddIndex(
            model_name='editorial',
            index=models.Index(fields=['problem_id', 'likes_count'], name='editorials_problem_e0674d_idx'),
        ),
        migrations.AddIndex(
            model_name='editorial',
            index=models.Index(fields=['author', 'created_at'], name='editorials_author__7d7961_idx'),
        ),
        migrations.AddIndex(
            model_name='editoriallike',
            index=models.Index(fields=['editorial', 'user'], name='editorial_l_editori_1e1fb0_idx'),
        ),
        migrations.AddIndex(
            model_name='editoriallike',
            index=models.Index(fields=['user', 'created_at'], name='editorial_l_user_id_ad0963_idx'),
        ),
        migrations.AddConstraint(
            model_name='editoriallike',
            constraint=models.UniqueConstraint(fields=('editorial', 'user'), name='unique_editorial_user_like'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', 'problem_id', 'created_at'], name='submissions_user_id_e2c2b6_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status', 'created_at'], name='submissions_status_3bfa4f_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionresult',
            index=models.Index(fields=['submission', 'test_case_index'], name='submission__submiss_cb29e7_idx'),
        ),
        migrations.AddIndex(
            model_name='userproblemquota',
            index=models.Index(fields=['user', 'problem_id', 'assignment_id'], name='user_proble_user_id_24c967_idx'),
        ),
        migrations.AddConstraint(
            model_name='userproblemquota',
            constraint=models.UniqueConstraint(fields=('user', 'problem_id', 'assignment_id'), name='unique_user_problem_assignment_quota'),
        ),
        migrations.AddIndex(
            model_name='userproblemsolvestatus',
            index=models.Index(fields=['user', 'problem_id'], name='user_proble_user_id_e40de6_idx'),
        ),
        migrations.AddIndex(
            model_name='userproblemsolvestatus',
            index=models.Index(fields=['user', 'solve_status'], name='user_proble_user_id_01e562_idx'),
        ),
        migrations.AddIndex(
            model_name='userproblemsolvestatus',
            index=models.Index(fields=['problem_id', 'solve_status'], name='user_proble_problem_11b932_idx'),
        ),
        migrations.AddConstraint(
            model_name='userproblemsolvestatus',
            constraint=models.UniqueConstraint(fields=('user', 'problem_id'), name='unique_user_problem_solve'),
        ),
        migrations.AddIndex(
            model_name='userproblemstats',
            index=models.Index(fields=['user', 'assignment_id', 'problem_id'], name='user_proble_user_id_6ff1de_idx'),
        ),
        migrations.AddIndex(
            model_name='userproblemstats',
            index=models.Index(fields=['assignment_id', 'best_score', 'first_ac_time'], name='user_proble_assignm_321609_idx'),
        ),
        migrations.AddConstraint(
            model_name='userproblemstats',
            constraint=models.UniqueConstraint(fields=('user', 'assignment_id', 'problem_id'), name='unique_user_assignment_problem'),
        ),
    ]
