# Generated by Django 5.2.7 on 2025-12-03 14:54

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('problem_id', models.IntegerField()),
                ('language_type', models.IntegerField(choices=[(0, 'C'), (1, 'C++'), (2, 'Python'), (3, 'Java'), (4, 'JavaScript')])),
                ('source_code', models.TextField()),
                ('input_data', models.TextField(blank=True, null=True)),
                ('expected_output', models.TextField(blank=True, null=True)),
                ('actual_output', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20)),
                ('execution_time', models.IntegerField(blank=True, null=True)),
                ('memory_usage', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'custom_tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('problem_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('difficulty_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('likes_count', models.IntegerField(default=0)),
                ('views_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_official', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'editorials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EditorialLike',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'editorial_likes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('problem_id', models.IntegerField()),
                ('language_type', models.IntegerField(choices=[(0, 'C'), (1, 'C++'), (2, 'Python'), (3, 'Java'), (4, 'JavaScript')])),
                ('source_code', models.TextField()),
                ('code_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('-2', 'Pending before upload'), ('-1', 'Pending'), ('0', 'Accepted'), ('1', 'Wrong Answer'), ('2', 'Compilation Error'), ('3', 'Time Limit Exceeded'), ('4', 'Memory Limit Exceeded'), ('5', 'Runtime Error'), ('6', 'Judge Error'), ('7', 'Output Limit Exceeded')], default='-1', max_length=30)),
                ('score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=100)),
                ('execution_time', models.IntegerField(default=-1)),
                ('memory_usage', models.IntegerField(default=-1)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('is_late', models.BooleanField(default=False)),
                ('is_custom_test', models.BooleanField(default=False)),
                ('penalty_applied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('attempt_number', models.IntegerField(default=1)),
                ('judge_server', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('judged_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('problem_id', models.IntegerField()),
                ('test_case_id', models.IntegerField()),
                ('test_case_index', models.IntegerField()),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer'), ('time_limit_exceeded', 'Time Limit Exceeded'), ('memory_limit_exceeded', 'Memory Limit Exceeded'), ('runtime_error', 'Runtime Error')], max_length=30)),
                ('execution_time', models.IntegerField(blank=True, null=True)),
                ('memory_usage', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=100)),
                ('output_preview', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('judge_message', models.TextField(blank=True, null=True)),
                ('solve_status', models.CharField(choices=[('unsolved', 'Unsolved'), ('partial', 'Partial'), ('solved', 'Solved')], default='unsolved', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'submission_results',
                'ordering': ['test_case_index'],
            },
        ),
        migrations.CreateModel(
            name='UserProblemQuota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('problem_id', models.IntegerField()),
                ('assignment_id', models.IntegerField(blank=True, null=True)),
                ('total_quota', models.IntegerField(default=-1)),
                ('remaining_attempts', models.IntegerField(default=-1)),
                ('reset_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_problem_quotas',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProblemSolveStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('problem_id', models.IntegerField()),
                ('total_submissions', models.IntegerField(default=0)),
                ('ac_submissions', models.IntegerField(default=0)),
                ('best_score', models.IntegerField(default=0)),
                ('first_solve_time', models.DateTimeField(blank=True, null=True)),
                ('last_submission_time', models.DateTimeField(blank=True, null=True)),
                ('solve_status', models.CharField(choices=[('never_tried', 'Never Tried'), ('attempted', 'Attempted'), ('partial_solved', 'Partial Solved'), ('fully_solved', 'Fully Solved')], default='never_tried', max_length=20)),
                ('total_execution_time', models.BigIntegerField(default=0)),
                ('best_execution_time', models.IntegerField(blank=True, null=True)),
                ('best_memory_usage', models.IntegerField(blank=True, null=True)),
                ('difficulty_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('tags_mastered', models.JSONField(default=dict)),
                ('mistake_patterns', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_problem_solve_status',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProblemStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_id', models.IntegerField()),
                ('problem_id', models.IntegerField()),
                ('total_submissions', models.IntegerField(default=0)),
                ('best_score', models.IntegerField(default=0)),
                ('max_possible_score', models.IntegerField(default=100)),
                ('first_ac_time', models.DateTimeField(blank=True, null=True)),
                ('last_submission_time', models.DateTimeField(blank=True, null=True)),
                ('solve_status', models.CharField(choices=[('unsolved', 'Unsolved'), ('partial', 'Partial'), ('solved', 'Solved')], default='unsolved', max_length=20)),
                ('best_execution_time', models.IntegerField(blank=True, null=True)),
                ('best_memory_usage', models.IntegerField(blank=True, null=True)),
                ('penalty_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('is_late', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_problem_stats',
                'ordering': ['-updated_at'],
            },
        ),
    ]
