# Generated by Django 5.2.7 on 2025-11-09 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='codedraft',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customtest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='editorial',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='editoriallike',
            name='editorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='submissions.editorial'),
        ),
        migrations.AddField(
            model_name='editoriallike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submissionresult',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='submissions.submission'),
        ),
        migrations.AddField(
            model_name='userproblemquota',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userproblemsolvestatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userproblemstats',
            name='best_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_for_stats', to='submissions.submission'),
        ),
        migrations.AddField(
            model_name='userproblemstats',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='codedraft',
            index=models.Index(fields=['user', 'problem_id', 'updated_at'], name='code_drafts_user_id_c5786c_idx'),
        ),
        migrations.AddIndex(
            model_name='codedraft',
            index=models.Index(fields=['user', 'assignment_id', 'updated_at'], name='code_drafts_user_id_31bc95_idx'),
        ),
        migrations.AddIndex(
            model_name='customtest',
            index=models.Index(fields=['user', 'created_at'], name='custom_test_user_id_4c32a4_idx'),
        ),
        migrations.AddIndex(
            model_name='customtest',
            index=models.Index(fields=['problem_id', 'created_at'], name='custom_test_problem_129fe5_idx'),
        ),
        migrations.AddIndex(
            model_name='editorial',
            index=models.Index(fields=['problem_id', 'is_official'], name='editorials_problem_79b740_idx'),
        ),
        migrations.AddIndex(
            model_name='editorial',
            index=models.Index(fields=['problem_id', 'likes_count'], name='editorials_problem_e0674d_idx'),
        ),
        migrations.AddIndex(
            model_name='editorial',
            index=models.Index(fields=['author', 'created_at'], name='editorials_author__7d7961_idx'),
        ),
        migrations.AddIndex(
            model_name='editoriallike',
            index=models.Index(fields=['editorial', 'user'], name='editorial_l_editori_1e1fb0_idx'),
        ),
        migrations.AddIndex(
            model_name='editoriallike',
            index=models.Index(fields=['user', 'created_at'], name='editorial_l_user_id_ad0963_idx'),
        ),
        migrations.AddConstraint(
            model_name='editoriallike',
            constraint=models.UniqueConstraint(fields=('editorial', 'user'), name='unique_editorial_user_like'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', 'problem_id', 'created_at'], name='submissions_user_id_e2c2b6_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status', 'created_at'], name='submissions_status_3bfa4f_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionresult',
            index=models.Index(fields=['submission', 'test_case_index'], name='submission__submiss_cb29e7_idx'),
        ),
        migrations.AddIndex(
            model_name='userproblemquota',
            index=models.Index(fields=['user', 'problem_id', 'assignment_id'], name='user_proble_user_id_24c967_idx'),
        ),
        migrations.AddConstraint(
            model_name='userproblemquota',
            constraint=models.UniqueConstraint(fields=('user', 'problem_id', 'assignment_id'), name='unique_user_problem_assignment_quota'),
        ),
        migrations.AddIndex(
            model_name='userproblemsolvestatus',
            index=models.Index(fields=['user', 'problem_id'], name='user_proble_user_id_e40de6_idx'),
        ),
        migrations.AddIndex(
            model_name='userproblemsolvestatus',
            index=models.Index(fields=['user', 'solve_status'], name='user_proble_user_id_01e562_idx'),
        ),
        migrations.AddIndex(
            model_name='userproblemsolvestatus',
            index=models.Index(fields=['problem_id', 'solve_status'], name='user_proble_problem_11b932_idx'),
        ),
        migrations.AddConstraint(
            model_name='userproblemsolvestatus',
            constraint=models.UniqueConstraint(fields=('user', 'problem_id'), name='unique_user_problem_solve'),
        ),
        migrations.AddIndex(
            model_name='userproblemstats',
            index=models.Index(fields=['user', 'assignment_id', 'problem_id'], name='user_proble_user_id_6ff1de_idx'),
        ),
        migrations.AddIndex(
            model_name='userproblemstats',
            index=models.Index(fields=['assignment_id', 'best_score', 'first_ac_time'], name='user_proble_assignm_321609_idx'),
        ),
        migrations.AddConstraint(
            model_name='userproblemstats',
            constraint=models.UniqueConstraint(fields=('user', 'assignment_id', 'problem_id'), name='unique_user_assignment_problem'),
        ),
    ]
