# Generated by Django 5.2.7 on 2025-12-27 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='editorial',
            name='editorials_problem_79b740_idx',
        ),
        migrations.RemoveField(
            model_name='editorial',
            name='difficulty_rating',
        ),
        migrations.RemoveField(
            model_name='editorial',
            name='is_official',
        ),
        migrations.RemoveField(
            model_name='editorial',
            name='title',
        ),
    ]
