# Generated by Django 5.2.7 on 2025-11-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_alter_editoriallike_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_custom_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('-2', 'No Code'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer'), ('time_limit_exceeded', 'Time Limit Exceeded'), ('memory_limit_exceeded', 'Memory Limit Exceeded'), ('runtime_error', 'Runtime Error'), ('compilation_error', 'Compilation Error'), ('system_error', 'System Error')], default='pending', max_length=30),
        ),
    ]
