# Generated by Django 5.2.7 on 2025-12-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_remove_editorial_editorials_problem_79b740_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionresult',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer'), ('compile_error', 'Compile Error'), ('time_limit_exceeded', 'Time Limit Exceeded'), ('memory_limit_exceeded', 'Memory Limit Exceeded'), ('runtime_error', 'Runtime Error')], max_length=30),
        ),
        migrations.AlterField(
            model_name='submissionresult',
            name='test_case_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
