# Generated by Django 5.2.7 on 2025-11-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_alter_submission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('-2', 'Pending before upload'), ('-1', 'Pending'), ('0', 'Accepted'), ('1', 'Wrong Answer'), ('2', 'Compilation Error'), ('3', 'Time Limit Exceeded'), ('4', 'Memory Limit Exceeded'), ('5', 'Runtime Error'), ('6', 'Judge Error'), ('7', 'Output Limit Exceeded')], default='-1', max_length=30),
        ),
    ]
