# Generated by Django 5.2.7 on 2025-12-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_alter_submissionresult_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissionresult',
            options={'ordering': ['subtask_id', 'test_case_index']},
        ),
        migrations.RemoveIndex(
            model_name='submissionresult',
            name='submission__submiss_cb29e7_idx',
        ),
        migrations.AddField(
            model_name='submissionresult',
            name='subtask_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submissionresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='submissionresult',
            unique_together={('submission', 'subtask_id', 'test_case_index')},
        ),
        migrations.AddIndex(
            model_name='submissionresult',
            index=models.Index(fields=['submission', 'subtask_id', 'test_case_index'], name='submission__submiss_37b35f_idx'),
        ),
    ]
