# Generated by Django 5.2.7 on 2025-11-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_alter_submission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codedraft',
            name='language_type',
            field=models.IntegerField(choices=[(0, 'C'), (1, 'C++'), (2, 'Python'), (3, 'Java'), (4, 'JavaScript')]),
        ),
        migrations.AlterField(
            model_name='customtest',
            name='language_type',
            field=models.IntegerField(choices=[(0, 'C'), (1, 'C++'), (2, 'Python'), (3, 'Java'), (4, 'JavaScript')]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='language_type',
            field=models.IntegerField(choices=[(0, 'C'), (1, 'C++'), (2, 'Python'), (3, 'Java'), (4, 'JavaScript')]),
        ),
    ]
