# Generated by Django 5.2.7 on 2025-11-28 12:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('join_code', models.CharField(blank=True, help_text='課程加入代碼（7 碼英數，大寫）。空值時會自動產生。', max_length=7, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{7}$', 'join_code 必須是 7 位大寫英數')])),
                ('student_limit', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('semester', models.CharField(blank=True, max_length=50)),
                ('academic_year', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('student_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher_id', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.PROTECT, related_name='courses_taught', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('score', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_grades', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='courses.courses')),
            ],
            options={
                'db_table': 'course_grades',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Course_members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('ta', 'Teaching Assistant'), ('teacher', 'Teacher')], default='student', max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_memberships', to=settings.AUTH_USER_MODEL)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='courses.courses')),
            ],
            options={
                'db_table': 'Course_members',
            },
        ),
        migrations.CreateModel(
            name='Batch_imports',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('csv_path', models.CharField(max_length=500)),
                ('file_size', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('import_result', models.BooleanField(null=True)),
                ('error_log', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports_created', to=settings.AUTH_USER_MODEL)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_imports', to='courses.courses')),
            ],
            options={
                'db_table': 'Batch_imports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('view_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_created', to=settings.AUTH_USER_MODEL)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='courses.courses')),
            ],
            options={
                'db_table': 'Announcements',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='courses',
            index=models.Index(fields=['join_code'], name='courses_join_co_3f36cc_idx'),
        ),
        migrations.AddIndex(
            model_name='courses',
            index=models.Index(fields=['is_active'], name='courses_is_acti_25e634_idx'),
        ),
        migrations.AddIndex(
            model_name='courses',
            index=models.Index(fields=['semester', 'academic_year'], name='courses_semeste_c3ee3c_idx'),
        ),
        migrations.AddIndex(
            model_name='coursegrade',
            index=models.Index(fields=['course', 'student'], name='course_grad_course__d9c3b2_idx'),
        ),
        migrations.AddIndex(
            model_name='course_members',
            index=models.Index(fields=['role'], name='Course_memb_role_00284b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='course_members',
            unique_together={('course_id', 'user_id')},
        ),
    ]
