# Generated by Django 5.2.6 on 2025-10-04 16:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('join_code', models.CharField(blank=True, help_text='課程加入代碼（7 碼英數，大寫）。空值時會自動產生。', max_length=7, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{7}$', 'join_code 必須是 7 位大寫英數')])),
                ('student_limit', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('semester', models.CharField(blank=True, max_length=50)),
                ('academic_year', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('student_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses_taught', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['join_code'], name='courses_join_co_3f36cc_idx'), models.Index(fields=['is_active'], name='courses_is_acti_25e634_idx'), models.Index(fields=['semester', 'academic_year'], name='courses_semeste_c3ee3c_idx')],
            },
        ),
    ]
