# Generated by Django 5.2.7 on 2025-12-17 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='creator_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batch_imports',
            name='imported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course_members',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursegrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courses',
            name='teacher_id',
            field=models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.PROTECT, related_name='courses_taught', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursegrade',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='courses.courses'),
        ),
        migrations.AddField(
            model_name='course_members',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='courses.courses'),
        ),
        migrations.AddField(
            model_name='batch_imports',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_imports', to='courses.courses'),
        ),
        migrations.AddField(
            model_name='announcements',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='courses.courses'),
        ),
        migrations.AddIndex(
            model_name='courses',
            index=models.Index(fields=['join_code'], name='courses_join_co_3f36cc_idx'),
        ),
        migrations.AddIndex(
            model_name='courses',
            index=models.Index(fields=['is_active'], name='courses_is_acti_25e634_idx'),
        ),
        migrations.AddIndex(
            model_name='courses',
            index=models.Index(fields=['semester', 'academic_year'], name='courses_semeste_c3ee3c_idx'),
        ),
        migrations.AddIndex(
            model_name='coursegrade',
            index=models.Index(fields=['course', 'student'], name='course_grad_course__d9c3b2_idx'),
        ),
        migrations.AddIndex(
            model_name='course_members',
            index=models.Index(fields=['role'], name='Course_memb_role_00284b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='course_members',
            unique_together={('course_id', 'user_id')},
        ),
    ]
