# Generated by Django 5.2.7 on 2025-11-06 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='courses',
            new_name='courses_join_co_3f36cc_idx',
            old_name='Courses_join_co_1d83b2_idx',
        ),
        migrations.RenameIndex(
            model_name='courses',
            new_name='courses_is_acti_25e634_idx',
            old_name='Courses_is_acti_de5639_idx',
        ),
        migrations.RenameIndex(
            model_name='courses',
            new_name='courses_semeste_c3ee3c_idx',
            old_name='Courses_semeste_422ae2_idx',
        ),
        migrations.AlterModelTable(
            name='courses',
            table='courses',
        ),
    ]
