# Generated by Django 5.2.7 on 2025-10-09 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_announcements_batchimports_coursemembers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='teacher',
            new_name='teacher_id',
        ),
        migrations.RenameIndex(
            model_name='coursemembers',
            new_name='Course_memb_role_00284b_idx',
            old_name='course_memb_role_fdef9b_idx',
        ),
        migrations.RenameIndex(
            model_name='courses',
            new_name='Courses_join_co_1d83b2_idx',
            old_name='courses_join_co_3f36cc_idx',
        ),
        migrations.RenameIndex(
            model_name='courses',
            new_name='Courses_is_acti_de5639_idx',
            old_name='courses_is_acti_25e634_idx',
        ),
        migrations.RenameIndex(
            model_name='courses',
            new_name='Courses_semeste_422ae2_idx',
            old_name='courses_semeste_c3ee3c_idx',
        ),
        migrations.AlterModelTable(
            name='announcements',
            table='Announcements',
        ),
        migrations.AlterModelTable(
            name='batchimports',
            table='Batch_imports',
        ),
        migrations.AlterModelTable(
            name='coursemembers',
            table='Course_members',
        ),
        migrations.AlterModelTable(
            name='courses',
            table='Courses',
        ),
    ]
