# Generated by Django 5.2.7 on 2025-11-09 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursegrade'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='coursegrade',
            new_name='course_grad_course__d9c3b2_idx',
            old_name='coursegrade_course_student_idx',
        ),
    ]
