# Generated by Django 5.2.7 on 2025-11-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_coursegrade_course_student_idx_course_grad_course__d9c3b2_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegrade',
            name='score',
            field=models.JSONField(),
        ),
    ]
