# Generated by Django 5.2.7 on 2025-12-03 14:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment_problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('special_judge', models.BooleanField(default=False)),
                ('time_limit', models.IntegerField(blank=True, null=True)),
                ('memory_limit', models.IntegerField(blank=True, null=True)),
                ('attempt_quota', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('partial_score', models.BooleanField(default=True)),
                ('hint_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'assignment_problems',
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Assignment_tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'assignment_tags',
            },
        ),
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('due_time', models.DateTimeField(blank=True, null=True)),
                ('late_penalty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('max_attempts', models.IntegerField(default=-1)),
                ('visibility', models.CharField(choices=[('public', 'public'), ('course_only', 'course_only'), ('hidden', 'hidden')], default='course_only', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('active', 'active'), ('closed', 'closed'), ('archived', 'archived')], default='draft', max_length=16)),
                ('ip_restriction', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assignments',
                'ordering': ['-created_at'],
            },
        ),
    ]
