# Generated by Django 5.2.7 on 2025-11-14 21:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('due_time', models.DateTimeField(blank=True, null=True)),
                ('late_penalty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('max_attempts', models.IntegerField(default=-1)),
                ('visibility', models.CharField(choices=[('public', 'public'), ('course_only', 'course_only'), ('hidden', 'hidden')], default='course_only', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('active', 'active'), ('closed', 'closed'), ('archived', 'archived')], default='draft', max_length=16)),
                ('ip_restriction', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.courses')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assignment_tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_assignments', to='problems.tags')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_tags', to='assignments.assignments')),
            ],
            options={
                'db_table': 'assignment_tags',
            },
        ),
        migrations.CreateModel(
            name='Assignment_problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('special_judge', models.BooleanField(default=False)),
                ('time_limit', models.IntegerField(blank=True, null=True)),
                ('memory_limit', models.IntegerField(blank=True, null=True)),
                ('attempt_quota', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('partial_score', models.BooleanField(default=True)),
                ('hint_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_assignments', to='problems.problems')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_problems', to='assignments.assignments')),
            ],
            options={
                'db_table': 'assignment_problems',
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='assignments',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__isnull', True), ('due_time__isnull', True), ('due_time__gte', models.F('start_time')), _connector='OR'), name='ck_assign_due_after_start_or_null'),
        ),
        migrations.AddConstraint(
            model_name='assignments',
            constraint=models.CheckConstraint(condition=models.Q(('late_penalty__gte', Decimal('0.00')), ('late_penalty__lte', Decimal('100.00'))), name='ck_assign_late_penalty_range'),
        ),
        migrations.AddConstraint(
            model_name='assignments',
            constraint=models.CheckConstraint(condition=models.Q(('max_attempts', -1), ('max_attempts__gte', 1), _connector='OR'), name='ck_assign_max_attempts_valid'),
        ),
        migrations.AddConstraint(
            model_name='assignment_tags',
            constraint=models.UniqueConstraint(fields=('assignment', 'tag'), name='uq_assignment_tag'),
        ),
        migrations.AddIndex(
            model_name='assignment_problems',
            index=models.Index(fields=['assignment', 'order_index'], name='idx_assignment_order'),
        ),
        migrations.AddConstraint(
            model_name='assignment_problems',
            constraint=models.UniqueConstraint(fields=('assignment', 'problem'), name='uq_assignment_problem'),
        ),
        migrations.AddConstraint(
            model_name='assignment_problems',
            constraint=models.CheckConstraint(condition=models.Q(('order_index__gte', 1)), name='ck_assignprob_order_ge_1'),
        ),
        migrations.AddConstraint(
            model_name='assignment_problems',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gte', Decimal('0.00'))), name='ck_assignprob_weight_ge_0'),
        ),
    ]
