# Generated by Django 5.2.7 on 2025-11-09 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('courses', '0001_initial'),
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_problems',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_assignments', to='problems.problems'),
        ),
        migrations.AddField(
            model_name='assignment_tags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_assignments', to='problems.tags'),
        ),
        migrations.AddField(
            model_name='assignments',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.courses'),
        ),
    ]
