# Generated by Django 5.2.7 on 2025-12-28 14:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment_tags',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_tags', to='assignments.assignments'),
        ),
        migrations.AddField(
            model_name='assignment_problems',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_problems', to='assignments.assignments'),
        ),
        migrations.AddConstraint(
            model_name='assignments',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__isnull', True), ('due_time__isnull', True), ('due_time__gte', models.F('start_time')), _connector='OR'), name='ck_assign_due_after_start_or_null'),
        ),
        migrations.AddConstraint(
            model_name='assignments',
            constraint=models.CheckConstraint(condition=models.Q(('late_penalty__gte', Decimal('0.00')), ('late_penalty__lte', Decimal('100.00'))), name='ck_assign_late_penalty_range'),
        ),
        migrations.AddConstraint(
            model_name='assignments',
            constraint=models.CheckConstraint(condition=models.Q(('max_attempts', -1), ('max_attempts__gte', 1), _connector='OR'), name='ck_assign_max_attempts_valid'),
        ),
        migrations.AddConstraint(
            model_name='assignment_tags',
            constraint=models.UniqueConstraint(fields=('assignment', 'tag'), name='uq_assignment_tag'),
        ),
        migrations.AddIndex(
            model_name='assignment_problems',
            index=models.Index(fields=['assignment', 'order_index'], name='idx_assignment_order'),
        ),
        migrations.AddConstraint(
            model_name='assignment_problems',
            constraint=models.UniqueConstraint(fields=('assignment', 'problem'), name='uq_assignment_problem'),
        ),
        migrations.AddConstraint(
            model_name='assignment_problems',
            constraint=models.CheckConstraint(condition=models.Q(('order_index__gte', 1)), name='ck_assignprob_order_ge_1'),
        ),
        migrations.AddConstraint(
            model_name='assignment_problems',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gte', Decimal('0.00'))), name='ck_assignprob_weight_ge_0'),
        ),
    ]
