# Generated by Django 5.2.7 on 2025-12-28 17:21

import assignments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='ip_whitelist',
            field=models.TextField(blank=True, validators=[assignments.models.validate_cidr_whitelist]),
        ),
    ]
