"""
Django settings for back_end project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECURITY WARNING: don't run with debug turned on in production!
# SECRET_KEY = 'django-insecure-7!jjwbdim67bist@b4_y$1mhva8x=v(1h$yaqv2!@391)#ji^e'
DEBUG = os.getenv("DJANGO_DEBUG", "True").lower() == "true"
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "dev-insecure-change-me")
ALLOWED_HOSTS = [h.strip() for h in os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",") if h.strip()]

CSRF_TRUSTED_ORIGINS = [h.strip() for h in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",") if h.strip()]

CORS_ALLOWED_ORIGINS = [h.strip() for h in os.getenv("CORS_ALLOWED_ORIGINS", "http://localhost:5173,http://127.0.0.1:5173").split(",") if h.strip()]
CORS_ALLOW_CREDENTIALS = True

# Application definition

INSTALLED_APPS = [
    # Unfold admin 必須放在 django.contrib.admin 之前
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user.apps.UserConfig',
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",  
    "corsheaders",
    "courses.apps.CoursesConfig",
    "auths",
    "problems",
    "assignments",
    "submissions",
    "api_tokens",
    "announcements",
    "profiles",
    "editor",
    "copycat",
    "search",
]

# Django Unfold Admin 配置
from django.templatetags.static import static
from django.urls import reverse_lazy

UNFOLD = {
    "SITE_TITLE": "NOJ Admin",
    "SITE_HEADER": "NOJ Online Judge",
    "SITE_SUBHEADER": "超級管理員後台",
    "SITE_URL": "/",
    # "SITE_ICON": lambda request: static("icon.svg"),  # 可選：自訂 icon
    "SITE_SYMBOL": "school",  # Material Symbols 圖示
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "ENVIRONMENT": "back_end.settings.environment_callback",
    "DASHBOARD_CALLBACK": "back_end.settings.dashboard_callback",
    "COLORS": {
        "primary": {
            "50": "250 245 255",
            "100": "243 232 255",
            "200": "233 213 255",
            "300": "216 180 254",
            "400": "192 132 252",
            "500": "168 85 247",
            "600": "147 51 234",
            "700": "126 34 206",
            "800": "107 33 168",
            "900": "88 28 135",
            "950": "59 7 100",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "首頁",
                "separator": True,
                "items": [
                    {
                        "title": "儀表板",
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },
            {
                "title": "使用者管理",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "使用者",
                        "icon": "person",
                        "link": reverse_lazy("admin:user_user_changelist"),
                    },
                    {
                        "title": "使用者資料",
                        "icon": "badge",
                        "link": reverse_lazy("admin:user_userprofile_changelist"),
                    },
                    {
                        "title": "API Tokens",
                        "icon": "key",
                        "link": reverse_lazy("admin:api_tokens_apitoken_changelist"),
                    },
                ],
            },
            {
                "title": "課程管理",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "課程",
                        "icon": "class",
                        "link": reverse_lazy("admin:courses_courses_changelist"),
                    },
                    {
                        "title": "課程成員",
                        "icon": "groups",
                        "link": reverse_lazy("admin:courses_course_members_changelist"),
                    },
                    {
                        "title": "課程公告",
                        "icon": "campaign",
                        "link": reverse_lazy("admin:courses_announcements_changelist"),
                    },
                    {
                        "title": "成績",
                        "icon": "grade",
                        "link": reverse_lazy("admin:courses_coursegrade_changelist"),
                    },
                    {
                        "title": "批次匯入",
                        "icon": "upload_file",
                        "link": reverse_lazy("admin:courses_batch_imports_changelist"),
                    },
                ],
            },
            {
                "title": "題目管理",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "題目",
                        "icon": "quiz",
                        "link": reverse_lazy("admin:problems_problems_changelist"),
                    },
                    {
                        "title": "子任務",
                        "icon": "format_list_numbered",
                        "link": reverse_lazy("admin:problems_problem_subtasks_changelist"),
                    },
                    {
                        "title": "測試案例",
                        "icon": "fact_check",
                        "link": reverse_lazy("admin:problems_test_cases_changelist"),
                    },
                    {
                        "title": "標籤",
                        "icon": "label",
                        "link": reverse_lazy("admin:problems_tags_changelist"),
                    },
                ],
            },
            {
                "title": "作業管理",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "作業",
                        "icon": "assignment",
                        "link": reverse_lazy("admin:assignments_assignments_changelist"),
                    },
                    {
                        "title": "作業題目",
                        "icon": "assignment_add",
                        "link": reverse_lazy("admin:assignments_assignment_problems_changelist"),
                    },
                ],
            },
            {
                "title": "提交管理",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "提交記錄",
                        "icon": "send",
                        "link": reverse_lazy("admin:submissions_submission_changelist"),
                    },
                    {
                        "title": "提交結果",
                        "icon": "checklist",
                        "link": reverse_lazy("admin:submissions_submissionresult_changelist"),
                    },
                    {
                        "title": "題解",
                        "icon": "lightbulb",
                        "link": reverse_lazy("admin:submissions_editorial_changelist"),
                    },
                    {
                        "title": "自訂測試",
                        "icon": "science",
                        "link": reverse_lazy("admin:submissions_customtest_changelist"),
                    },
                ],
            },
            {
                "title": "系統設定",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "群組",
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
        ],
    },
    "TABS": [
        {
            "models": ["user.user"],
            "items": [
                {
                    "title": "使用者",
                    "link": reverse_lazy("admin:user_user_changelist"),
                },
                {
                    "title": "使用者資料",
                    "link": reverse_lazy("admin:user_userprofile_changelist"),
                },
            ],
        },
        {
            "models": ["problems.problems", "problems.problem_subtasks", "problems.test_cases"],
            "items": [
                {
                    "title": "題目",
                    "link": reverse_lazy("admin:problems_problems_changelist"),
                },
                {
                    "title": "子任務",
                    "link": reverse_lazy("admin:problems_problem_subtasks_changelist"),
                },
                {
                    "title": "測試案例",
                    "link": reverse_lazy("admin:problems_test_cases_changelist"),
                },
            ],
        },
    ],
}

def environment_callback(request):
    """
    回傳當前環境標籤
    """
    from django.conf import settings as conf_settings
    if conf_settings.DEBUG:
        return ["開發環境", "warning"]
    return ["正式環境", "success"]

def dashboard_callback(request, context):
    """
    自訂儀表板上下文
    """
    from user.models import User
    from problems.models import Problems
    from submissions.models import Submission
    from courses.models import Courses
    
    context.update({
        "custom_stats": [
            {"title": "使用者總數", "value": User.objects.count(), "icon": "person"},
            {"title": "題目總數", "value": Problems.objects.count(), "icon": "quiz"},
            {"title": "提交總數", "value": Submission.objects.count(), "icon": "send"},
            {"title": "課程總數", "value": Courses.objects.count(), "icon": "class"},
        ],
    })
    return context

AUTH_USER_MODEL = 'user.User'
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'api_tokens.authentication.ApiTokenAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
        "user.permissions.IsEmailVerified",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "30/min",     # 未登入
        "user": "120/min",    # 已登入
        "send_email": "1/min",     # 例如寄驗證信
        "reset_pw": "5/hour",   # 重設密碼
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'back_end.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'back_end.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'ATOMIC_REQUESTS': False,
    }
}

# Redis Cache Configuration
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'SOCKET_CONNECT_TIMEOUT': 0.5,  # 500ms 連線超時
            'SOCKET_TIMEOUT': 0.5,  # 500ms 操作超時
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 50,
                'retry_on_timeout': True,
            },
            'REDIS_CLIENT_KWARGS': {
                'health_check_interval': 30,
            },
        },
        'KEY_PREFIX': 'noj',
        'TIMEOUT': 300,  # 預設 5 分鐘
    }
}

# Cache TTL settings
CACHE_TIMEOUTS = {
    'submission_list': 30,        # 30秒
    'user_stats': 300,            # 5分鐘
    'submission_detail': 120,     # 2分鐘
    'high_score': 600,            # 10分鐘
    'permission': 60,             # 1分鐘
    'ranking': 300,               # 5分鐘
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),     # 你可調整
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),        # 你可調整
    "ROTATE_REFRESH_TOKENS": True,                      # 旋轉 refresh（建議開）
    "BLACKLIST_AFTER_ROTATION": True,                   # 舊 refresh 自動黑名單
    "UPDATE_LAST_LOGIN": True,                          # 可選
}

SPECTACULAR_SETTINGS = {
    "TITLE": "New NOJ API Documentation",
    "DESCRIPTION": "目前後端實作的NOJ API文件(會根據程式碼自動生成)",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,

}

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"

DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)

FRONTEND_BASE_URL = os.getenv("FRONTEND_BASE_URL", "http://127.0.0.1:5173")
# MOSS User ID(環境變數讀取)
MOSS_USER_ID = int(os.getenv('MOSS_USER_ID', 0))
# ====================
# Celery Configuration
# ====================
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://127.0.0.1:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Taipei'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 分鐘硬限制

# ====================
# Sandbox Configuration
# ====================
SANDBOX_API_URL = os.getenv('SANDBOX_API_URL', 'http://34.81.90.111:8000')
SANDBOX_TIMEOUT = int(os.getenv('SANDBOX_TIMEOUT', '30'))  # API 請求超時（秒）
SANDBOX_API_KEY = os.getenv('SANDBOX_API_KEY', '')  # API Key for authentication

# ====================
# Backend Configuration
# ====================
BACKEND_BASE_URL = os.getenv('BACKEND_BASE_URL', 'http://localhost:8000')  # Backend 公開網址（用於 Sandbox callback）
